:experimental:
:imagesdir: ../../assets/images

= Before You Start

The workshop runs on a pre-provisioned IBM Techzone environment with a Red Hat OpenShift, a VM with IBM Bob, and a watsonx Orchestrate instance. You will not need to install anything on your laptop.

You will work through the modules in order with each module building on the previous one, so you will need to complete them in sequence.


== Click-to-Copy

Throughout the instructions, you will see various code and command blocks which can be copy/pasted directly by clicking anywhere on the block of text:

[source,java,role="copypaste"]
----
/* A sample Java snippet that you can copy/paste by clicking */
public class CopyMeDirectly {
    public static void main(String[] args) {
        System.out.println("You can copy this whole class with a click!");
    }
}
----

Simply click once and the whole block is copied to your clipboard, ready to be pasted with [CTRL+V] (or [Command+V] on Mac OS).

There are also Linux shell commands that can also be copied and pasted into a Terminal in your Development Environment:

[source,sh,role="copypaste"]
----
echo "This is a bash shell command that you can copy/paste by clicking"
----

In the next few sections, you will perform some setup tasks to prepare your environment for the workshop. You will need to do these only once, and they will take about 15 minutes.